spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://jelani.db.elephantsql.com:5432/gnxmsrxo
    username: gnxmsrxo
    password: Bz1sQ5Am7K8QB9qyVsRvOvmvddPBw48x
    continueOnError: true
  jpa:
    hibernate:
      ddl-auto: update
